# fly.toml app configuration file generated for creature-swift-agent on 2024-06-27T16:24:16+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'creature-swift-agent'
primary_region = 'waw'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
